name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  verify_files:
    name: Verify Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.17.1
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'
      - name: Install Packages
        run: pnpm install --frozen-lockfile
      - name: Lint Files
        run: pnpm run lint
      - name: Typecheck
        run: pnpm run typecheck

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.17.1
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'
      - name: Install Packages
        run: pnpm install --frozen-lockfile
      - name: Unit Tests
        run: pnpm run test

  examples:
    name: Build examples
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.17.1
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'
      - name: Install Packages
        run: pnpm install --frozen-lockfile
      - name: Build app-builder
        run: pnpm run build
      - name: Rebuild bin links
        run: pnpm install --frozen-lockfile
      - name: Build examples
        run: pnpm --filter "@examples/*" build
